// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EnvironmentVariableProvider")>]
[<assembly: AssemblyProductAttribute("EnvironmentVariableProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type provider for getting environment variables.")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EnvironmentVariableProvider"
    let [<Literal>] AssemblyProduct = "EnvironmentVariableProvider"
    let [<Literal>] AssemblyDescription = "Type provider for getting environment variables."
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
